### ISSUE TITLE
Impossible to install version 1.0.4

### ISSUE THREAD

**Issue by SkypLabs** [scaleway/packer-plugin-scaleway#36]
#### Overview of the Issue

When trying to install the latest version of the Packer plug-in for Scaleway, I get the following error:

```
$ packer init build.pkr.hcl
Failed getting the "github.com/hashicorp/scaleway" plugin:
1 error occurred:
        * could not get sha256 checksum file for github.com/hashicorp/scaleway version 1.0.4. Is the file present on the release and correctly named ? GET https://github.com
/scaleway/packer-plugin-scaleway/releases/download/v1.0.4/packer-plugin-scaleway_v1.0.4_SHA256SUMS: 404  []
```

It turns out Git tag 1.0.4 exists but not the GitHub release which is supposed to come with it, hence the missing checksum file.

#### Reproduction Steps

Here is my `packer` configuration block:

```hcl
packer {                                                                                                                                                                     
  required_plugins {
    scaleway = {
      source  = "github.com/hashicorp/scaleway"
      version = ">= 1.0.0"
    }
  }
}
```

Then just run `packer init <filename>` to get the error mentioned in the "Overview of the Issue" section.

### Plugin and Packer version

Packer v1.8.1.

### Simplified Packer Buildfile

See "Reproduction Steps" section.

### Operating system and Environment details

Not relevant.

### Log Fragments and crash.log files

N/A

**Comment by Codelax** [comment]
This is fixed with 1.0.5, our publishing pipeline is fixed
